#!/bin/bash
CPASSWD=`cat /etc/condor/condor_password`
/usr/sbin/condor_store_cred -p "$CPASSWD" -f /etc/condor/password_file
chmod ugo-x /etc/condor/password_file
chmod go-wx /etc/condor/password_file
chmod o-r /etc/condor/password_file
