#!/bin/bash
# mounthome    Selects largest unmounted disk, formats it, and mounts as /home
#
# chkconfig: 2345 02 98
# description: Selects largest unmounted disk, formats it, and mounts as /home
#

# Source function library.
. /etc/init.d/functions

# pull in sysconfig settings
[ -f /etc/sysconfig/mounthome ] && . /etc/sysconfig/mounthome

RETVAL=0

prog="mounthome"

start() {
    echo -n $"Starting mounthome: "
	/usr/bin/mounthome
}

case "$1" in
start)
        start
        ;;
status)
        status_at
        ;;
*)
        echo $"Usage: $0 {start|status}"
        exit 1
esac

exit $?
exit $RETVAL